### ISSUE TITLE
While executing the site I am getting 404 error

### ISSUE THREAD

**Issue by Libbna** [vbadkar/Activity#35]
![image](https://user-images.githubusercontent.com/46792570/133484377-388ee704-007d-44a0-bf21-589706e405bb.png)
Tried to run on different localhost but still getting same error.

**Comment by vbadkar** [comment]
Can you also include screenshot of the header?, I cant see the URL you are entering

**Comment by Libbna** [comment]
I'm running this on localhost: 8889, which you mentioned in or db file @vbadkar

**Comment by Libbna** [comment]
Issue resolved. The issue was from my side only I was executing the site on the wrong localhost. And I was also entering the database password wrong,
