### ISSUE TITLE
Remove any reference to htdocs or /var/www/html in the codebase. 

### ISSUE THREAD

**Issue by JayKandari** [vbadkar/Activity#40]
Eg: 
in .htaccess https://github.com/vbadkar/Activity/blob/main/.htaccess#L9 there is refernce to htdocs. All paths should be relative.

Add comments to your .htaccess file.

**Comment by vbadkar** [comment]
Reference to htdocs has been removed and code is running without any issues. @JayKandari Can you please verify this?

**Comment by JayKandari** [comment]
Verified the reference to htdocs is removed. Closing this.
