### ISSUE TITLE
Header: Menu options not aligned with logo and font size seem to be too small. 

### ISSUE THREAD

**Issue by asmita2** [vbadkar/Activity#48]
1. Update font size of menu options.
2. Logo and menu options should be aligned on same line.

**Comment by vbadkar** [comment]
Fixed this issue, @asmita2 Can you please verify this?
![Screenshot from 2021-09-23 01-44-28](https://user-images.githubusercontent.com/87715018/134415387-33c49f4e-2d67-4c19-9a35-53773cb1fd08.png)

**Comment by asmita2** [comment]
Styling seems good to me considering the screenshot. But please update scss indentation.
